### ISSUE TITLE
Use consumed and delivered energy metrics

### ISSUE THREAD

**Issue by cwasicki** [frequenz-floss/frequenz-reporting-python#18]
So far we only use the single energy metric, which is the sum of consumed and produced energy over the time period.
https://github.com/frequenz-floss/frequenz-reporting-python/blob/426615ebef3f8e3f89900f0c903599429ac8f8ce/src/frequenz/reporting/_reporting.py#L46
To reflect the independent measurements of the consumed and produced parts, we should switch to `METRIC_AC_ACTIVE_ENERGY_CONSUMED` and `METRIC_AC_ACTIVE_ENERGY_DELIVERED`:
https://github.com/frequenz-floss/frequenz-api-common/blob/8c3fc4fe42357b776f363722cda374116484d174/proto/frequenz/api/common/v1/metrics/metric_sample.proto#L132

FYI @flora-hofmann-frequenz

**Comment by flora-hofmann-frequenz** [comment]
We do split `METRIC_AC_ACTIVE_ENERGY` into positive (consumption) and negative (production). Would that not already give us the information of `ENERGY_CONSUMED` and `ENERGY_DELIVERED`?

The way I understood it, is that we would like to use energy instead of power in the way that we already showcase this [Deepnote Notebook](https://deepnote.com/workspace/Frequenz-30b27450-f7a3-4895-98f0-b368eca2b9b0/project/Energy-Demo-19dddaee-7ca0-45de-aa9a-f88fcf8c56c0/notebook/97e88e81c8f740a9a0193d4bfd5b8c67).
